version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.2
    container_name: logstash
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"

  apache:
    image: httpd:2.4
    container_name: apache
    volumes:
      - ./apache/logs:/usr/local/apache2/logs/
      - ./apache/html:/usr/local/apache2/htdocs/
      - ./apache/logs:/var/log/apache2
    ports:
      - "80:80"

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.2
    container_name: filebeat
    volumes:
      - ./filebeat/config:/usr/share/filebeat/config
      - ./filebeat/data:/usr/share/filebeat/data
      - ./apache/logs:/usr/share/filebeat/logs
    depends_on:
      - elasticsearch
      - logstash
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - LOGSTASH_HOST=logstash

volumes:
  esdata:

